version: "3"
services:
  krakend_ce:
    # The :watch image restarts the service automatically hen the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:2.5.0-watch
    container_name: krakend
    volumes:
      - ./config/krakend:/etc/krakend
      - ./auth-plugin:/opt/krakend/plugins/
    environment:
      - FC_ENABLE=1
      - FC_SETTINGS=/etc/krakend/settings
      - FC_PARTIALS=/etc/krakend/partials
      - FC_TEMPLATES=/etc/krakend/templates
      - FC_OUT=out.json
      - SERVICE_NAME=KrakenD API Gateway
      - SERVICE_NAME2=test
      - ENV=dev
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: [ "run", "-dc", "/etc/krakend/krakend.tmpl", "" ]
    networks:
      - shared_network
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:http://35.154.14.191:4000
  #     - "15672:15672"
  # influxdb:
  #   container_name: influx
  #   image: influxdb:1.8.10
  #   environment:
  #     - "INFLUXDB_DB=krakend"
  #     - "INFLUXDB_USER=krakend-dev"
  #     - "INFLUXDB_USER_PASSWORD=pas5w0rd"
  #     - "INFLUXDB_ADMIN_USER=admin"
  #     - "INFLUXDB_ADMIN_PASSWORD=supersecretpassword"
  #   ports:
  #     - "8086:8086"
  #   networks:
  #     - shared_network
  # grafana:
  #   image: grafana/grafana:9.1.2
  #   ports:
  #     - "4000:3000"
  #   volumes:
  #     - ./config/grafana/datasources/all.yml:/etc/grafana/provisioning/datasources/all.yml
  #     - ./config/grafana/dashboards/all.yml:/etc/grafana/provisioning/dashboards/all.yml
  #     - ./config/grafana/krakend:/var/lib/grafana/dashboards/krakend
  #   networks:
  #     - shared_network
  # elasticsearch:
  #   container_name: elasticsearch
  #   image: elasticsearch:8.4.1
  #   environment:
  #     - "discovery.type=single-node"
  #     - "xpack.security.enabled=false"
  #     - "xpack.security.transport.ssl.enabled=false"
  #     - "xpack.security.http.ssl.enabled=false"
  #   ports:
  #     - "19200:9200"
  #     - "9300:9300"
  #   networks:
  #     - shared_network
  # jaeger:
  #   container_name: jaeger
  #   image: jaegertracing/all-in-one:1
  #   environment:
  #     - SPAN_STORAGE_TYPE=elasticsearch
  #     - ES_SERVER_URLS=http://elasticsearch:9300
  #   ports:
  #     - "16686:16686"
  #     - "14268:14268"
  #   networks:
  #     - shared_network
networks:
  shared_network:
    external: true